<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <Version>17.4.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SlimLib.Auth.Azure" Version="11.3.0" />
  </ItemGroup>

</Project>
